### ISSUE TITLE
This kind of "secret" file should NOT be refered in an open source

### ISSUE THREAD

**Issue by tuanta** [iwayvietnam/esg-docker#1]
https://github.com/iwayvietnam/esg-docker/blob/479624710dfce3e52f007ea0464dabc44032b0d4/install/template/bayes/bayes_db.sh#L4

Why don't you put it to this git repo as well?

**Comment by hieunguyen23** [comment]
Because the file is > 100MB, github doesn't allow that. I used zip to compress it, it's ok. Thank you.
