### ISSUE TITLE
Is its required to enable external repos?

### ISSUE THREAD

**Issue by tuanta** [iwayvietnam/esg-docker#2]
These external repos are enabled:
- https://github.com/iwayvietnam/esg-docker/blob/master/install/build.sh#L27
- https://github.com/iwayvietnam/esg-docker/blob/479624710dfce3e52f007ea0464dabc44032b0d4/install/build.sh#L43

Is it mandatory?
There are no suitable packages in Rocky Linux standard repos?

**Comment by hieunguyen23** [comment]
it isn't mandatory, as mariadb already exists in the Rocky Linux representation standard but version 10.3 (not the latest). 
With mariadb_repo_setup being the latest version, currently 10.6.

**Comment by tuanta** [comment]
So you should not add MariaDB external repo.

How about Remi repo for PHP?
Should it also removed?

**Comment by hieunguyen23** [comment]
> So you should not add MariaDB external repo.
> 
> How about Remi repo for PHP?
> Should it also remove

Yes, should use packages in Rocky Linux standard repos for PHP and Mariadb.
